### ISSUE TITLE
testtable segfaults in 5.0.14

### ISSUE THREAD

**Issue by felixonmars** [fcitx/fcitx5-chinese-addons#104]
```
[0/1] Running tests...
Test project /build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14
    Start 1: testpunctuation
1/6 Test #1: testpunctuation ..................   Passed    0.01 sec
    Start 2: testpinyinhelper
2/6 Test #2: testpinyinhelper .................   Passed    0.33 sec
    Start 3: testfullwidth
3/6 Test #3: testfullwidth ....................   Passed    0.02 sec
    Start 4: testchttrans
4/6 Test #4: testchttrans .....................   Passed    0.17 sec
    Start 5: testpinyin
5/6 Test #5: testpinyin .......................   Passed    0.58 sec
    Start 6: testtable
6/6 Test #6: testtable ........................***Exception: SegFault  0.34 sec

83% tests passed, 1 tests failed out of 6

Total Test time (real) =   1.45 sec

The following tests FAILED:
          6 - testtable (SEGFAULT)
Errors while running CTest
Output from these tests are in: /build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
FAILED: CMakeFiles/test.util
cd /build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14 && /usr/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
```

Coredumpctl info:
```
                Module /usr/lib/libIMEPinyin.so.1.0.13 with build-id 3ce0e2faabb2e616e68a4238ad3dadf7d7733f74
                Module /usr/lib/libIMETable.so.1.0.13 with build-id 034e582cd1fcc13427f5733471951e7e51529dcf
                Module /build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14/im/table/libtable.so with build-id 11d1c1d967f5ff1242fd88ddf3ac1d6ac2beec7e
                Module /build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14/modules/punctuation/libpunctuation.so with build-id d962deeb54c8f9125431ed4a6a0f2ab0f199d887
                Module /usr/lib/libIMECore.so.1.0.13 with build-id 293e7c263b4529f3882344d2fe8d03986d9f6116
                Module /build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14/modules/pinyinhelper/libpinyinhelper.so with build-id 51640f758131d5564cc49a8da4ddafb8783ee705
                Module /usr/lib/fcitx5/libtestim.so with build-id dee7f73b5dd04461507eda75777c3f71df363fab
                Module /usr/lib/fcitx5/libquickphrase.so with build-id 280868c91952c5fc510c98c88b36864f4d15a6a2
                Module /usr/lib/libxkbcommon.so.0.0.0 with build-id 6cf66eead3fcc20fe5df10162bfbcdcdc8b2a183
                Module /usr/lib/libFcitx5Utils.so.5.0.18 with build-id 0c6f5167ccdae85066dd3bd13d4755983fc26312
                Module /usr/lib/libFcitx5Config.so.5.0.18 with build-id cf49e471509ea74b115097fd6ac751ccc9777446
                Module /usr/lib/libFcitx5Core.so.5.0.18 with build-id cb963df5581b97dfef3e6b2c75ddc9b0122f44b3
                Module /usr/lib/fcitx5/libtestfrontend.so with build-id ad49f9f66d3697f51882bd124d0bf022066ab7df
                Module linux-vdso.so.1 with build-id 0a9dd56f2d1d7d248eeef56d29e78f6fddab09d4
                Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                Module libz.so.1 with build-id fefe3219a96d682ec98fcfb78866b8594298b5a2
                Module libboost_iostreams.so.1.79.0 with build-id dd831804c130dbd1606a380bd5e22e7cfb493b04
                Module libgpg-error.so.0 with build-id 4738b8a9478177c202cccd64e0eb65d3dea2bfae
                Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                Module libzstd.so.1 with build-id ab54c2881f53ab314e134f3e08c76d504376dd5d
                Module liblzma.so.5 with build-id 28b40c7af8098a66af6ee093b6986b91cad7694d
                Module libgcrypt.so.20 with build-id 8bf3cb884124273640de797a3e77d86c98434ea4
                Module libcap.so.2 with build-id 21b00ab76bb16fde56fd741f07233c78069f0579
                Module ld-linux-x86-64.so.2 with build-id 0effd0e43efa4468d3c31871c93af0b7f3005673
                Module libm.so.6 with build-id 1b7296ef9fd806e47060788389293c824b09ad72
                Module libsystemd.so.0 with build-id a220b34e873e29bb116d88be0bf11fac7089ef4d
                Module libuuid.so.1 with build-id 032a21acd159ee3902605e9911be5f86a7df7df9
                Module libc.so.6 with build-id 60df1df31f02a7b23da83e8ef923359885b81492
                Module libgcc_s.so.1 with build-id 0e3de903950e35ae59a5de8c00b1817a4a71ca01
                Module libstdc++.so.6 with build-id b3eaebcb5369487562e52dd8d016c9cd77f80c54
                Module testtable with build-id 7aa88f9c7a07a054d96287524ea8fb4e73f43841
                Stack trace of thread 25:
                #0  0x00007f60b5c01424 n/a (/usr/lib/libFcitx5Core.so.5.0.18 + 0x7c424)
                ELF object binary architecture: AMD x86-64
```

**Comment by felixonmars** [comment]
[LastTest.log](https://github.com/fcitx/fcitx5-chinese-addons/files/9035874/LastTest.log)

**Comment by felixonmars** [comment]
Backtrace with debug info:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe17d11d424 in fcitx::InputMethodEntry::uniqueName[abi:cxx11]() const () from /usr/lib/libFcitx5Core.so.7
(gdb) bt
#0  0x00007fe17d11d424 in fcitx::InputMethodEntry::uniqueName[abi:cxx11]() const () from /usr/lib/libFcitx5Core.so.7
#1  0x00007fe17c46c4a9 in fcitx::TableEngine::getConfigForInputMethod(fcitx::InputMethodEntry const&) const () from /data/archbuild/extra-x86_64/felix2/build/fcitx5-chinese-addons/src/fcitx5-chinese-addons-5.0.14/im/table/libtable.so
#2  0x000055938cca28fa in scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}::operator()() const ()
#3  0x000055938cca48fa in void std::__invoke_impl<void, scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}&>(std::__invoke_other, scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}&) ()
#4  0x000055938cca45ee in std::enable_if<is_invocable_r_v<void, scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}&>, void>::type std::__invoke_r<void, scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}&>(scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}&) ()
#5  0x000055938cca40d5 in std::_Function_handler<void (), scheduleEvent(fcitx::EventDispatcher*, fcitx::Instance*)::{lambda()#3}>::_M_invoke(std::_Any_data const&) ()
#6  0x00007fe17d024f4b in ?? () from /usr/lib/libFcitx5Utils.so.2
#7  0x00007fe17d01b713 in ?? () from /usr/lib/libFcitx5Utils.so.2
#8  0x00007fe17cb9b9eb in ?? () from /usr/lib/libsystemd.so.0
#9  0x00007fe17cba6046 in sd_event_dispatch () from /usr/lib/libsystemd.so.0
#10 0x00007fe17cba62c9 in sd_event_run () from /usr/lib/libsystemd.so.0
#11 0x00007fe17cba64a0 in sd_event_loop () from /usr/lib/libsystemd.so.0
#12 0x00007fe17d019eb6 in fcitx::EventLoop::exec() () from /usr/lib/libFcitx5Utils.so.2
#13 0x00007fe17d0df0c7 in fcitx::Instance::exec() () from /usr/lib/libFcitx5Core.so.7
#14 0x000055938cca3920 in main ()
```

**Comment by wengxt** [comment]
fixed
